blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail, name='post_detail'),
]

myProject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.contrib import admin
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda req: redirect('/blog/')),  # Redirect from base URL to '/blog/'
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year, self.publish.month, self.publish.day, self.slug])

 #   class Meta:
  #      ordering = ('-publish',)

  #  def str(self):
    #    return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
class Meta:    #comentați clasa Meta existentă
    ordering = ('created',)
    def str(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.views.generic import ListView
from .models import Post, Comment
from .forms import CommentForm

def post_list(request):
    # Retrieve all Post objects from the database
    posts = Post.objects.all()

    # Render the 'list.html' template and pass the retrieved posts to it
    return render(request, 'blog/post/list.html', {'posts': posts})
from django.shortcuts import render, get_object_or_404
from .models import Post

def post_detail(request, year, month, day, post):
    # Retrieve a specific Post object based on the year, month, day, and post slug
    post = get_object_or_404(Post,
                             slug=post,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)

    # Render the 'detail.html' template and pass the retrieved post to it
    return render(request, 'blog/post/detail.html', {'post': post})


from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def post_list(request):
    object_list = Post.objects.all()
    paginator = Paginator(object_list, 3)  # 3 articole pe pagină

    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:  # Returnează prima pagină când numărul paginii nu este un întreg
        posts = paginator.page(1)
    except EmptyPage:  # Dacă numărul paginii este mai mare decât numărul total al paginilor, returnăm ultima pagină
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/post/list.html', {'page': page, 'posts': posts})

class PostListView(ListView):
    queryset = Post.objects.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, publish__year=year, publish__month=month, publish__day=day)

    comments = post.comments.filter(active=True)
    new_comment = None
    comment_form = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, 'blog/post/detail.html', {
        'post': post,
        'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form
    })

blog/templates/blog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="{% static 'images/icon.png' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="{% static 'css/blog.css' %}" rel="stylesheet" type="text/css" />
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary fixed-sticky">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'blog:post_list' %}">
            <img src="{% static 'images/logo.jpg' %}" alt="Logo" width="30" height="24" class="d-inline-block align-text-top">
            My Blog
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'blog:post_list' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'blog:post_list' %}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'blog:post_list' %}">Reviews</a>
                </li>
            </ul>
        </div>
    </div>
</nav>


    <div class="header"><h1>Welcome to My Blog's posts!</h1></div>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
    <div id="sidebar">
        <h2>My blog</h2>
        <img src="{% static 'images/imagine.jpg' %}" alt="Image" />
        <p>This is my blog.</p>
    </div>
    <footer class="footer">
        <p>Copyright &copy; Dianka</p>
    </footer>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/pagination.html
<div class="container">
    <div class="row justify-content-center">
        <div class="col-2">
            <nav aria-label="Page navigation">
                <ul class="pagination ">
                    {% if page.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% endif %}

                    {% for num in page.paginator.page_range %}
                        <li class="page-item {% if num == page.number %}active{% endif %}">
                            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                        </li>
                    {% endfor %}

                    {% if page.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
</div>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
{% load static %}
<link href="{% static 'css/blog.css' %}" rel="stylesheet" type="text/css" />
    <div class="container">
        <h1>{{ post.title }}</h1>
        <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
        <div class="row">
            <div class="col-md-12">
                {{ post.body|linebreaks }}

                {% with comments.count as total_comments %}
                    <h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
                {% endwith %}

                {% for comment in comments %}
                    <div class="comment">
                        <p class="info">
                            Comment {{ forloop.counter }} by {{ comment.name }}
                            {{ comment.created }}
                        </p>
                        {{ comment.body|linebreaks }}
                    </div>
                {% empty %}
                    <p>There are no comments yet.</p>
                {% endfor %}

                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#commentModal">
                    Add a Comment
                </button>

                <!-- Formular pt comentariu -->
                <div class="modal fade" id="commentModal" tabindex="-1" aria-labelledby="commentModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="commentModalLabel">Add a Comment</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <form method="post" class="comment-form">
                                    {% csrf_token %}
                                    {{ comment_form.as_p }}
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% block title %}My Blog{% endblock %}
{% block content %}
    {% for post in posts %}
        <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
        <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
        {{ post.body|truncatewords:30|linebreaks }}
    {% endfor %}
{% include "../pagination.html" with page=posts %}
{% endblock %}